# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rth_plot/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 718)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setStyleSheet("background-color:rgb(114, 159, 207)")
        self.centralWidget.setObjectName("centralWidget")
        self.frame_control = QtWidgets.QFrame(self.centralWidget)
        self.frame_control.setGeometry(QtCore.QRect(10, 10, 341, 701))
        self.frame_control.setStyleSheet("background:rgb(255, 255, 255)")
        self.frame_control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_control.setObjectName("frame_control")
        self.pushButton_plot = QtWidgets.QPushButton(self.frame_control)
        self.pushButton_plot.setGeometry(QtCore.QRect(40, 650, 251, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        self.pushButton_plot.setFont(font)
        self.pushButton_plot.setStyleSheet("background:rgb(238, 238, 236)")
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.pushButton_selectfile = QtWidgets.QPushButton(self.frame_control)
        self.pushButton_selectfile.setGeometry(QtCore.QRect(30, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        self.pushButton_selectfile.setFont(font)
        self.pushButton_selectfile.setStyleSheet("background:rgb(238, 238, 236)")
        self.pushButton_selectfile.setObjectName("pushButton_selectfile")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_control)
        self.textBrowser_2.setEnabled(True)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 20, 301, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_2.setLineWidth(0)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_control)
        self.frame_3.setGeometry(QtCore.QRect(20, 210, 301, 161))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 261, 39))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PlotAll = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.PlotAll.setStyleSheet("background:rgb(255, 255, 255)")
        self.PlotAll.setChecked(True)
        self.PlotAll.setObjectName("PlotAll")
        self.horizontalLayout_3.addWidget(self.PlotAll)
        self.PlotSelect = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.PlotSelect.setStyleSheet("background:rgb(255, 255, 255)")
        self.PlotSelect.setObjectName("PlotSelect")
        self.horizontalLayout_3.addWidget(self.PlotSelect)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 281, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_from = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_from.setStyleSheet("background:rgb(255, 255, 255)")
        self.frame_from.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_from.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_from.setObjectName("frame_from")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.frame_from)
        self.textBrowser_4.setEnabled(True)
        self.textBrowser_4.setGeometry(QtCore.QRect(10, 10, 261, 31))
        self.textBrowser_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.spinBox_from_m = QtWidgets.QSpinBox(self.frame_from)
        self.spinBox_from_m.setEnabled(False)
        self.spinBox_from_m.setGeometry(QtCore.QRect(80, 10, 48, 24))
        self.spinBox_from_m.setMaximum(999)
        self.spinBox_from_m.setObjectName("spinBox_from_m")
        self.spinBox_from_s = QtWidgets.QSpinBox(self.frame_from)
        self.spinBox_from_s.setEnabled(False)
        self.spinBox_from_s.setGeometry(QtCore.QRect(180, 10, 48, 24))
        self.spinBox_from_s.setMaximum(999)
        self.spinBox_from_s.setSingleStep(5)
        self.spinBox_from_s.setProperty("value", 30)
        self.spinBox_from_s.setObjectName("spinBox_from_s")
        self.verticalLayout.addWidget(self.frame_from)
        self.frame_to = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_to.setStyleSheet("background:rgb(255, 255, 255)")
        self.frame_to.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_to.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_to.setObjectName("frame_to")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.frame_to)
        self.textBrowser_5.setEnabled(True)
        self.textBrowser_5.setGeometry(QtCore.QRect(10, 10, 261, 41))
        self.textBrowser_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.spinBox_to_m = QtWidgets.QSpinBox(self.frame_to)
        self.spinBox_to_m.setEnabled(False)
        self.spinBox_to_m.setGeometry(QtCore.QRect(80, 10, 48, 24))
        self.spinBox_to_m.setMaximum(999)
        self.spinBox_to_m.setProperty("value", 5)
        self.spinBox_to_m.setDisplayIntegerBase(10)
        self.spinBox_to_m.setObjectName("spinBox_to_m")
        self.spinBox_to_s = QtWidgets.QSpinBox(self.frame_to)
        self.spinBox_to_s.setEnabled(False)
        self.spinBox_to_s.setGeometry(QtCore.QRect(180, 10, 48, 24))
        self.spinBox_to_s.setMaximum(999)
        self.spinBox_to_s.setSingleStep(5)
        self.spinBox_to_s.setObjectName("spinBox_to_s")
        self.verticalLayout.addWidget(self.frame_to)
        self.frame_4 = QtWidgets.QFrame(self.frame_control)
        self.frame_4.setGeometry(QtCore.QRect(20, 380, 301, 41))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser.setGeometry(QtCore.QRect(40, 8, 229, 31))
        self.textBrowser.setStyleSheet("background:rgb(255, 255, 255)")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setObjectName("textBrowser")
        self.JumpPointsValue = QtWidgets.QSpinBox(self.frame_4)
        self.JumpPointsValue.setGeometry(QtCore.QRect(200, 10, 41, 21))
        self.JumpPointsValue.setStyleSheet("background:rgb(255, 255, 255)")
        self.JumpPointsValue.setProperty("value", 2)
        self.JumpPointsValue.setObjectName("JumpPointsValue")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_control)
        self.textBrowser_3.setGeometry(QtCore.QRect(20, 100, 121, 41))
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textEdit_experiment = QtWidgets.QTextEdit(self.frame_control)
        self.textEdit_experiment.setGeometry(QtCore.QRect(20, 130, 301, 71))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        self.textEdit_experiment.setFont(font)
        self.textEdit_experiment.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit_experiment.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_experiment.setObjectName("textEdit_experiment")
        self.pushButton_selectlast = QtWidgets.QPushButton(self.frame_control)
        self.pushButton_selectlast.setGeometry(QtCore.QRect(180, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        self.pushButton_selectlast.setFont(font)
        self.pushButton_selectlast.setStyleSheet("background:rgb(238, 238, 236)")
        self.pushButton_selectlast.setObjectName("pushButton_selectlast")
        self.frame_log = QtWidgets.QFrame(self.centralWidget)
        self.frame_log.setGeometry(QtCore.QRect(360, 10, 751, 701))
        self.frame_log.setStyleSheet("background:rgb(255, 255, 255)")
        self.frame_log.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_log.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_log.setLineWidth(0)
        self.frame_log.setObjectName("frame_log")
        self.textEdit_log = QtWidgets.QTextEdit(self.frame_log)
        self.textEdit_log.setGeometry(QtCore.QRect(20, 60, 711, 571))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(13)
        self.textEdit_log.setFont(font)
        self.textEdit_log.setObjectName("textEdit_log")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.frame_log)
        self.textBrowser_6.setEnabled(True)
        self.textBrowser_6.setGeometry(QtCore.QRect(20, 20, 711, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_6.setFont(font)
        self.textBrowser_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_6.setLineWidth(0)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.pushButton_savelog = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_savelog.setGeometry(QtCore.QRect(930, 660, 131, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        self.pushButton_savelog.setFont(font)
        self.pushButton_savelog.setStyleSheet("background:rgb(238, 238, 236)")
        self.pushButton_savelog.setObjectName("pushButton_savelog")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.PlotSelect.clicked['bool'].connect(self.spinBox_from_m.setEnabled)
        self.PlotSelect.clicked['bool'].connect(self.spinBox_from_s.setEnabled)
        self.PlotSelect.clicked['bool'].connect(self.spinBox_to_m.setEnabled)
        self.PlotSelect.clicked['bool'].connect(self.spinBox_to_s.setEnabled)
        self.PlotAll.clicked['bool'].connect(self.spinBox_from_m.setDisabled)
        self.PlotAll.clicked['bool'].connect(self.spinBox_from_s.setDisabled)
        self.PlotAll.clicked['bool'].connect(self.spinBox_to_m.setDisabled)
        self.PlotAll.clicked['bool'].connect(self.spinBox_to_s.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RTHybrid Plot Tool"))
        self.pushButton_plot.setText(_translate("MainWindow", "Plot"))
        self.pushButton_selectfile.setText(_translate("MainWindow", "Select file"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">PLOT OPTIONS</span></p></body></html>"))
        self.PlotAll.setText(_translate("MainWindow", "Plot all file"))
        self.PlotSelect.setText(_translate("MainWindow", "Plot selected time"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">From:                m                  s</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">To:                    m                  s</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Downsampling:</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Experiment:</span></p></body></html>"))
        self.textEdit_experiment.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Write route or use select buttons...</p></body></html>"))
        self.pushButton_selectlast.setText(_translate("MainWindow", "Select last(beta)"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">LOG FILE</span></p></body></html>"))
        self.pushButton_savelog.setText(_translate("MainWindow", "Save file"))

